a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
result = a + b
print ( a, "+", b, "=", result)
result = a - b
print ( a, "-", b, "=", result)
result = a*b
print ( a, "*", b, "=", result)
result = a/b
print ( a, "/", b, "=", result)
